# Generated by Django 3.1.4 on 2021-01-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20210116_2159'),
        ('themedTour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themedpack',
            name='country',
        ),
        migrations.AddField(
            model_name='themedpack',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPanel.country'),
        ),
    ]
