# Generated by Django 3.1.4 on 2021-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themedTour', '0002_auto_20210122_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themedpackreview',
            name='permition',
            field=models.BooleanField(default=False, verbose_name='Display on front-end'),
        ),
    ]
