# Generated by Django 3.1.4 on 2021-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themedTour', '0003_auto_20210204_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='themedpack',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='themedpackreview',
            name='permition',
            field=models.BooleanField(default=False),
        ),
    ]
