# Generated by Django 3.1.4 on 2021-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themedTour', '0005_themedpack_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='themedpack',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
