# Generated by Django 3.1.4 on 2021-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_remove_themedpackreservation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='themedpackreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
