# Generated by Django 3.1.4 on 2021-01-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themedTour', '0002_auto_20210122_1455'),
        ('adminPanel', '0005_auto_20210124_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemedPackPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_start_date', models.DateField()),
                ('price_end_date', models.DateField()),
                ('dynamic_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('connect_pack_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themedTour.themedpack')),
            ],
        ),
    ]
