# Generated by Django 3.1.4 on 2021-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_themedpacktravelersquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themedpacktravelersquantity',
            name='dynamic_quantity',
            field=models.IntegerField(),
        ),
    ]
