# Generated by Django 3.1.4 on 2021-02-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_carmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.country')),
            ],
        ),
    ]
