# Generated by Django 3.1.4 on 2021-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_city_city_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='x_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='y_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
