# Generated by Django 3.1.4 on 2021-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themedpackreservation',
            name='calendar_price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
