# Generated by Django 3.1.4 on 2021-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='text2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='text3',
            field=models.TextField(default=''),
        ),
    ]
