# Generated by Django 3.1.4 on 2021-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_auto_20210503_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cover_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='top_title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
