# Generated by Django 3.1.4 on 2021-05-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0022_auto_20210503_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='WhyUs',
        ),
    ]
