# Generated by Django 3.1.4 on 2021-01-16 21:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('presentation_text', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=256)),
                ('picture1', models.ImageField(default='images/brand-2.jpg', upload_to='images/accomodation')),
                ('picture2', models.ImageField(blank=True, default='images/brand-2.jpg', null=True, upload_to='images/accomodation')),
                ('picture3', models.ImageField(blank=True, default='images/brand-2.jpg', null=True, upload_to='images/accomodation')),
                ('video', models.FileField(upload_to='accomodationvideos')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accommodation_type', models.CharField(choices=[('1', 'Hotel'), ('2', 'Apartment')], max_length=256)),
                ('destination', models.ManyToManyField(to='adminPanel.Country')),
            ],
            options={
                'verbose_name_plural': 'Accommodation',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(choices=[('1', 'Airport'), ('2', 'Hotel'), ('3', 'Agency')], max_length=256)),
                ('car_types', models.CharField(choices=[('1', 'Coupe'), ('2', 'Sedan'), ('3', 'Van')], max_length=256)),
                ('mark', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_of_sits', models.SmallIntegerField()),
                ('picture1', models.ImageField(default='images/brand-2.jpg', upload_to='images/cars')),
                ('picture2', models.ImageField(default='images/brand-2.jpg', upload_to='images/cars')),
                ('destination', models.ManyToManyField(to='adminPanel.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=128)),
                ('room_type', models.CharField(choices=[('1', 'Independent room'), ('2', 'Shared room'), ('3', 'Private room')], max_length=256)),
                ('room_description', models.CharField(choices=[('1', 'Twin'), ('2', 'Double'), ('3', 'Triple'), ('4', 'Shared')], max_length=256)),
                ('WiFi_connection', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('permition', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Car Reviews',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_of_apartment', models.CharField(choices=[('1', 'Studio'), ('2', 'F1'), ('3', 'F2'), ('4', 'F3'), ('5', 'F4'), ('6', 'villa')], max_length=256)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('WiFi_connection', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('permition', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accommodation Reviews',
            },
        ),
    ]
