# Generated by Django 3.1.4 on 2021-02-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='start_date',
        ),
    ]
