# Generated by Django 3.1.4 on 2021-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0002_auto_20210204_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
