# Generated by Django 3.1.4 on 2021-02-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0003_auto_20210204_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('1', 'Independent room'), ('2', 'Shared room'), ('3', 'Private room')], max_length=256)),
                ('room_description', models.CharField(choices=[('1', 'Twin'), ('2', 'Double'), ('3', 'Triple'), ('4', 'Shared')], max_length=256)),
                ('availability', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.hotel')),
            ],
        ),
    ]
