# Generated by Django 3.1.4 on 2021-02-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0005_auto_20210204_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationreview',
            name='permition',
            field=models.BooleanField(default=False, verbose_name='Display on front-end'),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='permition',
            field=models.BooleanField(default=False, verbose_name='Display on front-end'),
        ),
    ]
