# Generated by Django 3.1.4 on 2021-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0006_auto_20210206_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accommodationreview',
            name='permition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='permition',
            field=models.BooleanField(default=False),
        ),
    ]
