# Generated by Django 3.1.4 on 2021-02-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0008_auto_20210207_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationOrder',
        ),
    ]
