# Generated by Django 3.1.4 on 2021-02-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_carmark'),
        ('personalTour', '0009_delete_accommodationorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPanel.carmark'),
        ),
    ]
