# Generated by Django 3.1.4 on 2021-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0011_accommodationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='family',
            field=models.BooleanField(default=False),
        ),
    ]
