# Generated by Django 3.1.4 on 2021-02-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalTour', '0015_accommodation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pick_up_destination',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
