# Generated by Django 3.1.4 on 2021-03-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_city'),
        ('personalTour', '0020_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='destination',
        ),
        migrations.AddField(
            model_name='car',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPanel.country'),
        ),
    ]
