# Generated by Django 3.1.4 on 2021-03-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0021_auto_20210305_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='permission',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
