# Generated by Django 3.1.4 on 2021-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0022_auto_20210306_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
