# Generated by Django 3.1.4 on 2021-03-27 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalTour', '0023_hotelroom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_order_start_date', models.DateField()),
                ('room_order_end_date', models.DateField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.accommodation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
