# Generated by Django 3.1.4 on 2021-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0027_auto_20210327_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheckout',
            name='room_checkout',
            field=models.TextField(),
        ),
    ]
