# Generated by Django 3.1.4 on 2021-03-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0028_auto_20210327_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheckout',
            name='room_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalTour.hotelroom'),
        ),
    ]
