# Generated by Django 3.1.4 on 2021-04-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0029_auto_20210327_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
    ]
