# Generated by Django 3.1.4 on 2021-04-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0030_remove_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='availability',
        ),
    ]
