# Generated by Django 3.1.4 on 2021-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0036_auto_20210520_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='identification_number',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='identification_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
