# Generated by Django 3.1.1 on 2021-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0043_auto_20210702_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('1', 'Twin'), ('2', 'Double'), ('3', 'Triple'), ('4', 'Suite'), ('5', 'Suite deluxe'), ('6', 'Triple'), ('7', 'Shared')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(blank=True, choices=[('1', 'Independent room'), ('2', 'Shared room'), ('3', 'Private room'), ('4', 'Custom')], max_length=256, null=True),
        ),
    ]
