# Generated by Django 3.1.1 on 2021-07-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0045_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorder',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personalTour.order'),
        ),
    ]
