# Generated by Django 3.1.1 on 2021-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0048_auto_20210730_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorder',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=15),
        ),
    ]
