# Generated by Django 3.1.1 on 2021-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalTour', '0050_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='car', max_length=10),
        ),
    ]
