# Generated by Django 3.1.4 on 2020-12-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_footerdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdescription',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
