# Generated by Django 3.1.4 on 2020-12-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201220_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterDescription',
        ),
    ]
