# Generated by Django 3.1.4 on 2020-12-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_delete_footerdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontvideos',
            options={'verbose_name_plural': 'Front Videos'},
        ),
    ]
