# Generated by Django 3.1.4 on 2021-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201221_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('video', models.FileField(upload_to='homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageInterestingFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.AlterField(
            model_name='frontvideos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage'),
        ),
    ]
