# Generated by Django 3.1.4 on 2021-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210415_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
