# Generated by Django 3.1.4 on 2021-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_account_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
