# Generated by Django 3.1.4 on 2020-12-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
    ]
