# Generated by Django 3.1.4 on 2020-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_faq_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_type',
            field=models.CharField(choices=[('1', 'Pre-Sale Questions'), ('2', 'Other Type Questions')], default='1', max_length=256),
        ),
    ]
