# Generated by Django 3.1.4 on 2021-02-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_faq_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='permition',
            field=models.BooleanField(default=False, verbose_name='Display on front-end'),
        ),
    ]
