# Generated by Django 3.1.4 on 2021-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20210206_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='permition',
            field=models.BooleanField(default=False),
        ),
    ]
