# Generated by Django 3.1.4 on 2021-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
