# Generated by Django 3.1.4 on 2021-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_contact_send_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=127, null=True)),
                ('top_text', models.TextField()),
                ('cover_file', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=127)),
                ('image1', models.ImageField(upload_to='')),
                ('text1', models.TextField(default='')),
                ('image2', models.ImageField(upload_to='')),
                ('text2', models.TextField(default='')),
                ('image3', models.ImageField(upload_to='')),
                ('text3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=127)),
                ('text', models.TextField()),
            ],
        ),
    ]
