# Generated by Django 3.1.4 on 2021-05-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_about_vendor_whyus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
