# Generated by Django 3.1.4 on 2021-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20210513_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
